(* Generated by ocaml-rs *)

open! Bigarray

(* file: lib.rs *)

external getKeys: unit -> (int array * int array) = "getKeys"
external getProof: int array -> string -> string * int array = "getProof"
external verifyProof: int array -> string -> int array -> bool = "verifyProof"
